name: energy_pipeline
version: '1.0.0'
config-version: 2

profile: energy_pipeline

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  energy_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table